### PR TITLE
Hide real data

### PR DESCRIPTION
**Pull request by jeopard**

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
this project has been put on hold.
don't expect this to be merged

**Comment by kistitan** [comment]
The project is closed, but indeed it would make sense to remove this personal look data.
Got in contact with the team.

Thanks for the suggestion.

**Comment by reneklacan** [comment]
@kistitan Hey Krisztian, @jeopard is actually part of the team :D

**Comment by kistitan** [comment]
@reneklacan

Yes, it's totally safe to merge.

**Comment by reneklacan** [comment]
@kistitan thanks!

**Pull request merged**
