### PR TITLE
Signature field addition

### PR DESCRIPTION
**Pull request by ReluctantSub**
Ability to append a customized signature line, which is automatically
included when a message is sent.  

settings
sig

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
I really dislike this idea.
keep in mind the messages are aimed to be closer to IM/Chat than one off messages.
plus signatures are noisy

**Comment by ReluctantSub** [comment]
Well, it is isn't forced on the user, just an extra option available I always thought was missing. But I may be too much a traditionalist.

**Comment by kistitan** [comment]
Hi there, sorry for the late comment.

First of all I can't say thanks enough for contributing to our project and going into our code :)

I actually agree with both if you. Current chat is indeed more meant to be like instant messaging.
On the other hand it is true that it is not mandatory.

So from my side I see no problem with adding it.
The code seems to be correct :)

Let's see what others do say.

**Comment by johnbaku** [comment]
I love the initiative... but I am not a fan of it... I find signatures add noise to messages.

Sorry about that! :-/

**Comment by kistitan** [comment]
Sorry @ReluctantSub,

Based on the feedbacks we decided not to merge this to our main branch.

However please do not let this reduce your enthusiasm about contributing to our project.
We cannot express how much we do appreciate it.

I close this PR for now.

Have a happy new year ;)

**Pull request closed without merging**
