### PR TITLE
Notification settings

### PR DESCRIPTION
**Pull request by kistitan**
...and fix for app launcher name

### CODE REVIEW

**Comment by jacortinas** [comment]
👍 lgtm

**Comment by reneklacan** [comment]
screenshot pls!

**Comment by FernandoMiguel** [comment]
what was the issue? code base or android bug?

**Comment by kistitan** [comment]
I could not figure out, but I anyway needed a start activity to distribute the start sequence and for that I can set the app name so that will work for sure

**Comment by reneklacan** [comment]
✌️ LGTM

**Pull request merged**
